plugins {
    id 'scala'
    id 'java-library'
}

group = 'com.example'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.scala-lang:scala-library:2.13.12'
    implementation 'org.postgresql:postgresql:42.7.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

jar {
    manifest {
        attributes(
            'Implementation-Title': 'ScalaLib',
            'Implementation-Version': version
        )
    }

    archiveBaseName.set("scala-lib")
    archiveVersion.set("")
}

